import type { PresenceEvent, ReportedPresence } from "./monitor";

/** One state the filter can't reach: before the first window fills there is no verdict *and* no blackout. */
export type Status = ReportedPresence | "starting";

/**
 * What the user is shown, as opposed to what is reported to the API. Carries no signal strength:
 * the view only changes on a transition, so a number here would sit frozen at whatever it read when
 * the state last flipped. Live readings go to stdout, where they update every poll.
 *
 * `cause` is carried because `unknown` covers three different situations with three different things
 * to do about them, and a tray that said only "unknown" would leave the user to guess which.
 */
export interface StatusView {
  readonly status: Status;
  readonly cause: PresenceEvent["cause"] | null;
}

export const STARTING: StatusView = { status: "starting", cause: null };

export function viewOf(event: PresenceEvent): StatusView {
  return { status: event.presence, cause: event.cause };
}

export function statusTitle({ status, cause }: StatusView): string {
  switch (status) {
    case "starting":
      return "Getting a reading…";
    case "present":
      return "Phone is at your desk";
    case "away":
      return "Phone is away";
    case "unknown":
      return unknownTitle(cause);
  }
}

function unknownTitle(cause: PresenceEvent["cause"] | null): string {
  switch (cause) {
    case "bluetooth-off":
      return "Bluetooth is off on this Mac";
    case "cold-start":
      return "Haven't seen your phone yet";
    default:
      return "Can't see your phone";
  }
}

export function tooltip(view: StatusView): string {
  return `Perimeter — ${statusTitle(view)}`;
}

/** Basename of the tray template image; the files are generated by `scripts/make-tray-icons.mjs`. */
export function iconName({ status }: StatusView): string {
  switch (status) {
    case "starting":
      return "idleTemplate";
    case "present":
      return "presentTemplate";
    case "away":
      return "awayTemplate";
    case "unknown":
      return "unknownTemplate";
  }
}

export interface Nudge {
  readonly title: string;
  readonly body: string;
  /** Whether clicking it should open Bluetooth settings — only true when *this* Mac's radio is the problem. */
  readonly offersBluetoothSettings: boolean;
}

/**
 * `present` nudges on every arrival for now, session or not — a stand-in until the API exists and
 * its `{ notify }` decides, since only it knows active hours, breaks and cooldowns. `unknown` stays
 * local for good: it's the one case the sensor itself cannot resolve.
 *
 * No cooldown needed: the monitor emits transitions only, so one episode nudges once.
 */
export function nudgeFor(event: PresenceEvent): Nudge | null {
  if (event.presence === "present") {
    return {
      title: "Your phone is in range",
      body: "Take it out of the perimeter.",
      offersBluetoothSettings: false,
    };
  }
  if (event.presence !== "unknown") return null;

  switch (event.cause) {
    case "bluetooth-off":
      return {
        title: "Bluetooth is off",
        body: "Turn it back on — Perimeter can't see your phone without it.",
        offersBluetoothSettings: true,
      };
    case "cold-start":
      return {
        title: "Haven't seen your phone yet",
        body: "Nothing counts as focus until it turns up.",
        offersBluetoothSettings: false,
      };
    default:
      return {
        title: "Can't see your phone",
        body: "Is its Bluetooth off? This time doesn't count as focus.",
        offersBluetoothSettings: false,
      };
  }
}
